"""Theme constants for {{PROJECT_TITLE}}."""

from manim import BLACK, BLUE_C, GREY_B, WHITE, YELLOW_C

BACKGROUND = BLACK
FOREGROUND = WHITE
MUTED = GREY_B
PRIMARY = BLUE_C
ACCENT = YELLOW_C

TITLE_SIZE = 48
BODY_SIZE = 30
CAPTION_SIZE = 20
SAFE_MARGIN = 0.45
